// Code generated by qtc from "index.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/index/index.html:1
package index

//line templates/index/index.html:1
import "github.com/valyala/fasthttp"

//line templates/index/index.html:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/index/index.html:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/index/index.html:4
type IndexPage struct {
	CTX *fasthttp.RequestCtx
}

//line templates/index/index.html:9
func (p *IndexPage) StreamCSS(qw422016 *qt422016.Writer) {
//line templates/index/index.html:9
	qw422016.N().S(` `)
//line templates/index/index.html:9
}

//line templates/index/index.html:9
func (p *IndexPage) WriteCSS(qq422016 qtio422016.Writer) {
//line templates/index/index.html:9
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/index/index.html:9
	p.StreamCSS(qw422016)
//line templates/index/index.html:9
	qt422016.ReleaseWriter(qw422016)
//line templates/index/index.html:9
}

//line templates/index/index.html:9
func (p *IndexPage) CSS() string {
//line templates/index/index.html:9
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/index/index.html:9
	p.WriteCSS(qb422016)
//line templates/index/index.html:9
	qs422016 := string(qb422016.B)
//line templates/index/index.html:9
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/index/index.html:9
	return qs422016
//line templates/index/index.html:9
}

//line templates/index/index.html:11
func (p *IndexPage) StreamTitle(qw422016 *qt422016.Writer) {
//line templates/index/index.html:11
	qw422016.N().S(` HomePage `)
//line templates/index/index.html:11
}

//line templates/index/index.html:11
func (p *IndexPage) WriteTitle(qq422016 qtio422016.Writer) {
//line templates/index/index.html:11
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/index/index.html:11
	p.StreamTitle(qw422016)
//line templates/index/index.html:11
	qt422016.ReleaseWriter(qw422016)
//line templates/index/index.html:11
}

//line templates/index/index.html:11
func (p *IndexPage) Title() string {
//line templates/index/index.html:11
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/index/index.html:11
	p.WriteTitle(qb422016)
//line templates/index/index.html:11
	qs422016 := string(qb422016.B)
//line templates/index/index.html:11
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/index/index.html:11
	return qs422016
//line templates/index/index.html:11
}

//line templates/index/index.html:14
func (p *IndexPage) StreamBody(qw422016 *qt422016.Writer) {
//line templates/index/index.html:14
	qw422016.N().S(`

Muhammet Arslan

`)
//line templates/index/index.html:18
}

//line templates/index/index.html:18
func (p *IndexPage) WriteBody(qq422016 qtio422016.Writer) {
//line templates/index/index.html:18
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/index/index.html:18
	p.StreamBody(qw422016)
//line templates/index/index.html:18
	qt422016.ReleaseWriter(qw422016)
//line templates/index/index.html:18
}

//line templates/index/index.html:18
func (p *IndexPage) Body() string {
//line templates/index/index.html:18
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/index/index.html:18
	p.WriteBody(qb422016)
//line templates/index/index.html:18
	qs422016 := string(qb422016.B)
//line templates/index/index.html:18
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/index/index.html:18
	return qs422016
//line templates/index/index.html:18
}

//line templates/index/index.html:21
func (p *IndexPage) StreamJS(qw422016 *qt422016.Writer) {
//line templates/index/index.html:21
	qw422016.N().S(` `)
//line templates/index/index.html:21
}

//line templates/index/index.html:21
func (p *IndexPage) WriteJS(qq422016 qtio422016.Writer) {
//line templates/index/index.html:21
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/index/index.html:21
	p.StreamJS(qw422016)
//line templates/index/index.html:21
	qt422016.ReleaseWriter(qw422016)
//line templates/index/index.html:21
}

//line templates/index/index.html:21
func (p *IndexPage) JS() string {
//line templates/index/index.html:21
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/index/index.html:21
	p.WriteJS(qb422016)
//line templates/index/index.html:21
	qs422016 := string(qb422016.B)
//line templates/index/index.html:21
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/index/index.html:21
	return qs422016
//line templates/index/index.html:21
}
