// Code generated by qtc from "base.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/layout/base.html:1
package layout

//line templates/layout/base.html:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/layout/base.html:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/layout/base.html:2
type Base interface {
//line templates/layout/base.html:2
	CSS() string
//line templates/layout/base.html:2
	StreamCSS(qw422016 *qt422016.Writer)
//line templates/layout/base.html:2
	WriteCSS(qq422016 qtio422016.Writer)
//line templates/layout/base.html:2
	JS() string
//line templates/layout/base.html:2
	StreamJS(qw422016 *qt422016.Writer)
//line templates/layout/base.html:2
	WriteJS(qq422016 qtio422016.Writer)
//line templates/layout/base.html:2
	Title() string
//line templates/layout/base.html:2
	StreamTitle(qw422016 *qt422016.Writer)
//line templates/layout/base.html:2
	WriteTitle(qq422016 qtio422016.Writer)
//line templates/layout/base.html:2
	Body() string
//line templates/layout/base.html:2
	StreamBody(qw422016 *qt422016.Writer)
//line templates/layout/base.html:2
	WriteBody(qq422016 qtio422016.Writer)
//line templates/layout/base.html:2
}

//line templates/layout/base.html:10
func StreamBaseLayout(qw422016 *qt422016.Writer, b Base) {
//line templates/layout/base.html:10
	qw422016.N().S(`

<!DOCTYPE html>

<html lang="en">

	<!-- begin::Head -->
	<head>
		<base href="">
		<meta charset="utf-8" />
		 <title>`)
//line templates/layout/base.html:20
	b.StreamTitle(qw422016)
//line templates/layout/base.html:20
	qw422016.N().S(` | Muhammet Arslan</title>
		<meta name="description" content="Latest updates and statistic charts">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		`)
//line templates/layout/base.html:24
	b.StreamCSS(qw422016)
//line templates/layout/base.html:24
	qw422016.N().S(`
	</head>

	<!-- end::Head -->

	<!-- begin::Body -->
	<body>

		`)
//line templates/layout/base.html:32
	b.StreamBody(qw422016)
//line templates/layout/base.html:32
	qw422016.N().S(`

	</body>
		
		`)
//line templates/layout/base.html:36
	b.StreamJS(qw422016)
//line templates/layout/base.html:36
	qw422016.N().S(`

`)
//line templates/layout/base.html:38
}

//line templates/layout/base.html:38
func WriteBaseLayout(qq422016 qtio422016.Writer, b Base) {
//line templates/layout/base.html:38
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/layout/base.html:38
	StreamBaseLayout(qw422016, b)
//line templates/layout/base.html:38
	qt422016.ReleaseWriter(qw422016)
//line templates/layout/base.html:38
}

//line templates/layout/base.html:38
func BaseLayout(b Base) string {
//line templates/layout/base.html:38
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/layout/base.html:38
	WriteBaseLayout(qb422016, b)
//line templates/layout/base.html:38
	qs422016 := string(qb422016.B)
//line templates/layout/base.html:38
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/layout/base.html:38
	return qs422016
//line templates/layout/base.html:38
}
